### ISSUE TITLE
License for the repository

### ISSUE THREAD

**Issue by iandareid** [wiedehopf/wmm#1]
I am developing an open source autopilot, and this library looks like it will work perfectly. Could you add a license so I can know how I am able to use your code?

Thank you!

**Comment by wiedehopf** [comment]
This is problematic as the main code is not mine.
See:
https://github.com/wiedehopf/wmm2020/blob/master/geomag.c

https://www.ncei.noaa.gov/products/world-magnetic-model
(see third party software)

See also someone else using it with probably the correct notice that at least in the US no copyright applies: https://github.com/Mictronics/readsb-protobuf/blob/dev/geomag.c

So i'm hesitant to slap a license on any of this.

**Comment by iandareid** [comment]
Fantastic, thank you for the resources. I will take that under advisement.

**Comment by wiedehopf** [comment]
Added the copyright notice as it seems appropriate.

Also added a license file ... that should be compatible with the original copyright notice ... i hope.
